import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import {
  Type,
  Hash,
  CheckSquare,
  CircleDot,
  Tags,
  Calendar,
  Link,
  Mail,
  Phone,
  User,
  Paperclip,
  Clock,
  UserCheck,
  Search,
} from 'lucide-react'
import { Input } from '@/components/ui/input'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'
<<<<<<< HEAD
import type { PropertySchema } from '@/hooks/use-databases'
=======
import type { PropertySchema } from '@/hooks/use-database'
>>>>>>> d4609d4 (feat: add hooks for managing spaces, users, versions, and webhooks)

interface AddPropertyPopoverProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onAdd: (property: PropertySchema) => Promise<void>
  trigger: React.ReactNode
}

// Default select options
const defaultSelectOptions = [
  { id: 'option_1', name: 'Option 1', color: 'gray' },
  { id: 'option_2', name: 'Option 2', color: 'blue' },
  { id: 'option_3', name: 'Option 3', color: 'green' },
]

// Default status options
const defaultStatusOptions = [
  { id: 'not_started', name: 'Not started', color: 'gray' },
  { id: 'in_progress', name: 'In progress', color: 'blue' },
  { id: 'done', name: 'Done', color: 'green' },
]

export function AddPropertyPopover({
  open,
  onOpenChange,
  onAdd,
  trigger,
}: AddPropertyPopoverProps) {
  const { t } = useTranslation('database')
  const [searchQuery, setSearchQuery] = useState('')
  const [propertyName, setPropertyName] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)

  // Property types organized like Notion
  const basicTypes = [
    { type: 'text', name: t('properties.text'), icon: Type, description: t('properties.textDescription') },
    { type: 'number', name: t('properties.number'), icon: Hash, description: t('properties.numberDescription') },
    { type: 'select', name: t('properties.select'), icon: CircleDot, description: t('properties.selectDescription') },
    { type: 'multi_select', name: t('properties.multiSelect'), icon: Tags, description: t('properties.multiSelectDescription') },
    { type: 'status', name: t('properties.status'), icon: CircleDot, description: t('properties.statusDescription') },
    { type: 'date', name: t('properties.date'), icon: Calendar, description: t('properties.dateDescription') },
    { type: 'person', name: t('properties.person'), icon: User, description: t('properties.personDescription') },
    { type: 'checkbox', name: t('properties.checkbox'), icon: CheckSquare, description: t('properties.checkboxDescription') },
    { type: 'url', name: t('properties.url'), icon: Link, description: t('properties.urlDescription') },
    { type: 'email', name: t('properties.email'), icon: Mail, description: t('properties.emailDescription') },
    { type: 'phone', name: t('properties.phone'), icon: Phone, description: t('properties.phoneDescription') },
  ]

  const advancedTypes = [
    { type: 'files', name: t('properties.files'), icon: Paperclip, description: t('properties.filesDescription') },
    { type: 'relation', name: t('properties.relation'), icon: Link, description: t('properties.relationDescription') },
    { type: 'rollup', name: t('properties.rollup'), icon: Hash, description: t('properties.rollupDescription') },
    { type: 'formula', name: t('properties.formula'), icon: Hash, description: t('properties.formulaDescription') },
  ]

  const systemTypes = [
    { type: 'created_time', name: t('properties.createdTime'), icon: Clock, description: t('properties.autoGenerated') },
    { type: 'created_by', name: t('properties.createdBy'), icon: UserCheck, description: t('properties.autoGenerated') },
    { type: 'last_edited_time', name: t('properties.lastEditedTime'), icon: Clock, description: t('properties.autoGenerated') },
    { type: 'last_edited_by', name: t('properties.lastEditedBy'), icon: UserCheck, description: t('properties.autoGenerated') },
  ]

  const allTypes = [...basicTypes, ...advancedTypes, ...systemTypes]
  const filteredTypes = searchQuery
    ? allTypes.filter(
        (t) =>
          t.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
          t.description.toLowerCase().includes(searchQuery.toLowerCase())
      )
    : null

  const handleTypeSelect = async (type: string) => {
    const typeInfo = allTypes.find((t) => t.type === type)
    const name = propertyName.trim() || typeInfo?.name || 'New property'

    setIsSubmitting(true)
    try {
      const id = `prop_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`

      const property: PropertySchema = {
        id,
        name,
        type,
      }

      // Add default options for select types
      if (type === 'select' || type === 'multi_select') {
        property.options = { options: defaultSelectOptions }
      } else if (type === 'status') {
        property.options = { options: defaultStatusOptions }
      }

      await onAdd(property)
      onOpenChange(false)
      setSearchQuery('')
      setPropertyName('')
    } catch (error) {
      console.error('Failed to add property:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  const renderTypeItem = (typeInfo: (typeof basicTypes)[0], compact = false) => {
    const Icon = typeInfo.icon
    if (compact) {
      return (
        <button
          key={typeInfo.type}
          className="flex items-center gap-2 px-2 py-1.5 text-sm hover:bg-accent rounded-sm transition-colors disabled:opacity-50"
          onClick={() => handleTypeSelect(typeInfo.type)}
          disabled={isSubmitting}
          title={typeInfo.description}
        >
          <Icon className="h-4 w-4 text-muted-foreground shrink-0" />
          <span className="truncate">{typeInfo.name}</span>
        </button>
      )
    }
    return (
      <button
        key={typeInfo.type}
        className="w-full flex items-center gap-3 px-3 py-2 text-sm hover:bg-accent rounded-sm transition-colors disabled:opacity-50"
        onClick={() => handleTypeSelect(typeInfo.type)}
        disabled={isSubmitting}
      >
        <Icon className="h-4 w-4 text-muted-foreground shrink-0" />
        <div className="flex-1 text-left">
          <div className="font-medium">{typeInfo.name}</div>
        </div>
      </button>
    )
  }

  return (
    <Popover open={open} onOpenChange={onOpenChange}>
      <PopoverTrigger asChild>{trigger}</PopoverTrigger>
      <PopoverContent
        className="w-80 p-0"
        align="start"
        sideOffset={4}
      >
        {/* Search/Name input */}
        <div className="p-2 border-b">
          <div className="relative">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              value={searchQuery || propertyName}
              onChange={(e) => {
                const value = e.target.value
                setSearchQuery(value)
                setPropertyName(value)
              }}
              placeholder={t('properties.typePropertyName')}
              className="h-8 pl-8 text-sm"
              autoFocus
            />
          </div>
        </div>

        {/* Type list */}
        <div className="max-h-80 overflow-y-auto py-1">
          {filteredTypes ? (
            // Search results
            filteredTypes.length > 0 ? (
              <div className="px-1">
                {filteredTypes.map((typeInfo) => renderTypeItem(typeInfo))}
              </div>
            ) : (
              <div className="px-3 py-6 text-center text-sm text-muted-foreground">
                {t('properties.noMatchingTypes')}
              </div>
            )
          ) : (
            // Grouped list with grid layout
            <>
              {/* Basic section */}
              <div className="px-3 py-1.5">
                <div className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                  {t('properties.basic')}
                </div>
              </div>
              <div className="px-1 grid grid-cols-2 gap-0.5">
                {basicTypes.map((typeInfo) => renderTypeItem(typeInfo, true))}
              </div>

              {/* Advanced section */}
              <div className="px-3 py-1.5 mt-2">
                <div className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                  {t('properties.advanced')}
                </div>
              </div>
              <div className="px-1 grid grid-cols-2 gap-0.5">
                {advancedTypes.map((typeInfo) => renderTypeItem(typeInfo, true))}
              </div>

              {/* System section */}
              <div className="px-3 py-1.5 mt-2">
                <div className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                  {t('properties.system')}
                </div>
              </div>
              <div className="px-1 grid grid-cols-2 gap-0.5">
                {systemTypes.map((typeInfo) => renderTypeItem(typeInfo, true))}
              </div>
            </>
          )}
        </div>
      </PopoverContent>
    </Popover>
  )
}
